name: interactive_viewer_sample
description: Flutter InteractiveViewer Sample

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_state_notifier:
  freezed_annotation:
  state_notifier:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  grinder:

flutter:
  uses-material-design: true
  assets:
    - assets/